Style: change name

diff --git a/pigs-add b/pigs-add
--- a/pigs-add
+++ b/pigs-add
@@ -7,13 +7,13 @@ default_repo=".pig"
 
 if ! test -d "$default_repo"
 then
-    echo "$0: error: pigs repository directory $default_repo not found"
+    echo "$0: error: pigs repository directory $default_repo not found" >&2
     exit 1
 fi 
 
 if [ $# -eq 0 ]
 then
-    echo "usage: $0 <filenames>"
+    echo "usage: $0 <filenames>" >&2
     exit 1
 fi
 
@@ -23,38 +23,19 @@ fi
 index_file="./$default_repo/index"
 objects_file="./$default_repo/objects"
 
-# populate index file, treat it as temp tree
-branch_info="$default_repo/BRANCHES"
-curr_branch=$(cat $default_repo/HEAD)
-curr_tree=$(cat $branch_info | grep -E "^$curr_branch" | cut -d' ' -f2)
-
-if ! [ "$curr_tree" = "empty" ]
-then
-    cat "$objects_file/$curr_tree" >> "$index_file"
-fi 
-tmp=$(sort -u "$index_file")
-echo "$tmp" > "$index_file"
-
-# check if file exist in index
+# check if file exist in index, or current directory
 for file in "$@"
 do
     if ! (grep -E "^$file" "$index_file" > /dev/null || test -f "$file")
     then
-        echo "$0: error: can not open '$file'" 
+        echo "$0: error: can not open '$file'" >&2
         exit 1
     fi 
 done 
 
-tmp_idx=$(mktemp)
-
-if [ -n "$(cat "$index_file")" ]
-then 
-    cat "$index_file" >> "$tmp_idx"
-fi
-
 for file in "$@"
 do 
-    # might introduce lost pointers, will fix later
+    # might introduce lost pointers, might fix if i have time
     if ! test -f "$file"
     then
         continue
@@ -68,8 +49,18 @@ do
     else 
         cat "$file" > "$objects_file/$content_hash"
     fi 
-    echo "$file $content_hash" >> "$tmp_idx"
-done 
 
-sort -u "$tmp_idx" > "$index_file"
-rm "$tmp_idx"
+    if grep -E "^$file" "$index_file" > /dev/null
+    then
+        tmp=$(sed -E "s/^$file .*$/$file $content_hash/" "$index_file")
+
+        if [ -n "$tmp" ]
+        then 
+            echo "$tmp" > "$index_file"
+        else 
+            : > "$index_file"
+        fi 
+    else 
+        echo "$file $content_hash" >> "$index_file"
+    fi 
+done 
diff --git a/pigs-log b/pigs-log
--- a/pigs-log
+++ b/pigs-log
@@ -7,15 +7,19 @@ default_repo=".pig"
 
 if ! test -d "$default_repo"
 then
-    echo "$0: error: pigs repository directory $default_repo not found"
+    echo "$0: error: pigs repository directory $default_repo not found" >&2
     exit 1
 fi 
 
 if ! [ $# -eq 0 ]
 then
-    echo "usage: $0"
+    echo "usage: $0" >&2
     exit 1
 fi
 
+# =====================================
+# Main
+# =====================================
+
 curr_branch=$(cat $default_repo/HEAD)
-cat "$default_repo/logs/$curr_branch"
+tac "$default_repo/logs/$curr_branch"
