Chore: fix and test

diff --git a/pigs-add b/pigs-add
--- a/pigs-add
+++ b/pigs-add
@@ -7,13 +7,13 @@ default_repo=".pig"
 
 if ! test -d "$default_repo"
 then
-    echo "$0: error: pigs repository directory $default_repo not found" >&2
+    echo "pigs-add: error: pigs repository directory $default_repo not found" >&2
     exit 1
 fi 
 
 if [ $# -eq 0 ]
 then
-    echo "usage: $0 <filenames>" >&2
+    echo "usage: pigs-add <filenames>" >&2
     exit 1
 fi
 
@@ -28,7 +28,7 @@ for file in "$@"
 do
     if ! (grep -E "^$file .*$" "$index_file" > /dev/null || test -f "$file")
     then
-        echo "$0: error: can not open '$file'" >&2
+        echo "pigs-add: error: can not open '$file'" >&2
         exit 1
     fi 
 done 
diff --git a/pigs-branch b/pigs-branch
--- a/pigs-branch
+++ b/pigs-branch
@@ -7,7 +7,7 @@ default_repo=".pig"
 
 if ! test -d "$default_repo"
 then
-    echo "$0: error: pigs repository directory $default_repo not found" >&2
+    echo "pigs-branch: error: pigs repository directory $default_repo not found" >&2
     exit 1
 fi 
 
@@ -30,7 +30,7 @@ fi
 curr_branch=$(cat "$default_repo/HEAD")
 if [ -z "$(cat "$default_repo/logs/$curr_branch")" ]
 then
-    echo "$0: error: this command can not be run until after the first commit" >&2
+    echo "pigs-branch: error: this command can not be run until after the first commit" >&2
     exit 1
 fi 
 
@@ -54,7 +54,7 @@ fi
 
 if [ -z "$branch_input" ] || echo "$branch_input" | grep -E "^-" > /dev/null
 then
-    echo "$0: error: branch name required"
+    echo "pigs-branch: error: branch name required"
     exit 1
 fi  
 
@@ -68,13 +68,30 @@ if [ "$delete" -eq 1 ]
 then 
     if ! branch_exist "$branch_input"
     then
-        echo "$0: error: branch '$branch_input' doesn't exist" >&2
+        echo "pigs-branch: error: branch '$branch_input' doesn't exist" >&2
         exit 1
     fi 
 
-    if [ "$branch_input" = "master" ]
+
+    if [ "$branch_input" = "$curr_branch" ]
     then
-        echo "$0: error: can not delete branch 'master': default branch" >&2
+        msg="pigs-branch: error: can not delete branch '$branch_input':"
+
+        if [ "$branch_input" = "master" ]
+        then
+            echo "$msg default branch" >&2
+        else 
+            echo "$msg current branch" >&2 
+        fi 
+        exit 1 
+    fi 
+
+    curr_branch_hash=$(sed -nE "s/^$curr_branch (.*)$/\1/p" "$default_repo/BRANCHES")
+    branch_input_hash=$(sed -nE "s/^$branch_input (.*)$/\1/p" "$default_repo/BRANCHES")
+
+    if ! [ "$curr_branch_hash" = "$branch_input_hash" ]
+    then
+        echo "pigs-branch: error: branch '$branch_input' has unmerged changes" >&2
         exit 1 
     fi 
 
@@ -91,7 +108,7 @@ fi
 
 if branch_exist "$branch_input"
 then
-    echo "$0: error: branch '$branch_input' already exists" >&2
+    echo "pigs-branch: error: branch '$branch_input' already exists" >&2
     exit 1    
 fi 
 
diff --git a/pigs-checkout b/pigs-checkout
--- a/pigs-checkout
+++ b/pigs-checkout
@@ -7,7 +7,7 @@ default_repo=".pig"
 
 if ! test -d "$default_repo"
 then
-    echo "$0: error: pigs repository directory $default_repo not found" >&2
+    echo "pigs-checkout: error: pigs repository directory $default_repo not found" >&2
     exit 1
 fi 
 
@@ -23,7 +23,7 @@ fi
 
 if ! grep -E "^$1 .*$" "$default_repo/BRANCHES" > /dev/null
 then
-    echo "$0: error: unknown branch '$1'" >&2
+    echo "pigs-checkout: error: unknown branch '$1'" >&2
     exit 1
 fi 
 
@@ -42,7 +42,7 @@ curr_branch=$(cat "$default_repo/HEAD")
 curr_tree=$(grep -E "^$curr_branch .*$" "$default_repo/BRANCHES" | cut -d' ' -f2)
 
 will_overwrite=$(mktemp)
-overwrite_error="$0: error: Your changes to the following files would be overwritten by checkout:"
+overwrite_error="pigs-checkout: error: Your changes to the following files would be overwritten by checkout:"
 
 file_whitelist=$(mktemp -d)
 files=$(ls .)
diff --git a/pigs-commit b/pigs-commit
--- a/pigs-commit
+++ b/pigs-commit
@@ -7,13 +7,13 @@ default_repo=".pig"
 
 if ! test -d "$default_repo"
 then
-    echo "$0: error: pigs repository directory $default_repo not found" >&2
+    echo "pigs-commit: error: pigs repository directory $default_repo not found" >&2
     exit 1
 fi 
 
-error_msg="usage: $0 [-a] -m commit-message"
+error_msg="usage: pigs-commit [-a] -m commit-message"
 
-if [ $# -eq 0 ]
+if [ $# -eq 0 ] || [ $# -gt 3 ]
 then
     echo "$error_msg" >&2
     exit 1
@@ -21,12 +21,11 @@ fi
 
 if ! [ "$1" = "-m" ] && ! [ "$1" = "-a" ] && ! [ "$1" = "-am" ]
 then
-    echo "hi"
     echo "$error_msg" >&2
     exit 1
 fi
 
-if { [ "$1" = "-m" ] || [ "$1" = "-am" ]; } && [ -z "$2" ]
+if { [ "$1" = "-m" ] || [ "$1" = "-am" ]; } && { [ -z "$2" ] || [ "$2" = "-a" ]; }
 then
     echo "$error_msg" >&2
     exit 1
@@ -59,7 +58,7 @@ index_file="$default_repo/index"
 if [ "$1" = "-a" ] || [ "$1" = "-am" ]
 then
     files_in_index=$(cut -d' ' -f1 "$index_file" | tr '\n' ' ') # very hacky
-    eval "pigs-add $files_in_index"
+    eval "pigs-add $files_in_index" > /dev/null
 fi 
 
 no_commits="nothing to commit"
diff --git a/pigs-init b/pigs-init
--- a/pigs-init
+++ b/pigs-init
@@ -4,7 +4,7 @@ pigs_dir=".pig"
 
 if test -e "$pigs_dir"
 then
-    echo "$0: error: $pigs_dir already exists" >&2
+    echo "pigs-init: error: $pigs_dir already exists" >&2
     exit 1
 fi
 
diff --git a/pigs-log b/pigs-log
--- a/pigs-log
+++ b/pigs-log
@@ -7,13 +7,13 @@ default_repo=".pig"
 
 if ! test -d "$default_repo"
 then
-    echo "$0: error: pigs repository directory $default_repo not found" >&2
+    echo "pigs-log: error: pigs repository directory $default_repo not found" >&2
     exit 1
 fi 
 
 if ! [ $# -eq 0 ]
 then
-    echo "usage: $0" >&2
+    echo "usage: pigs-log" >&2
     exit 1
 fi
 
diff --git a/pigs-rm b/pigs-rm
--- a/pigs-rm
+++ b/pigs-rm
@@ -7,11 +7,11 @@ default_repo=".pig"
 
 if ! test -d "$default_repo"
 then
-    echo "$0: error: pigs repository directory $default_repo not found" >&2
+    echo "pigs-rm: error: pigs repository directory $default_repo not found" >&2
     exit 1
 fi 
 
-usage="usage: $0 [--force] [--cached] <filenames>"
+usage="usage: pigs-rm [--force] [--cached] <filenames>"
 if [ $# -eq 0 ]
 then 
     echo "$usage" >&2
@@ -68,7 +68,7 @@ do
     # check if file exist
     if ! grep -E "^$file .*$" "$index_file" > /dev/null
     then
-        echo "$0: error: '$file' is not in the pigs repository" >&2
+        echo "pigs-rm: error: '$file' is not in the pigs repository" >&2
         exit 1 
     fi 
 
@@ -83,9 +83,9 @@ do
         # index == curr && index != tree => stage error
         # index != curr && index != tree => index_error
         # index == tree && index != curr => repo_error
-        stage_error="$0: error: '$file' has staged changes in the index"
-        index_error="$0: error: '$file' in index is different to both the working file and the repository"
-        repo_error="$0: error: '$file' in the repository is different to the working file"
+        stage_error="pigs-rm: error: '$file' has staged changes in the index"
+        index_error="pigs-rm: error: '$file' in index is different to both the working file and the repository"
+        repo_error="pigs-rm: error: '$file' in the repository is different to the working file"
 
         index_file_hash=$(sed -nE "s/^$file (.*)$/\1/p" "$index_file")
         curr_file_hash=$(sha1sum "$file" | cut -d' ' -f1)
diff --git a/pigs-show b/pigs-show
--- a/pigs-show
+++ b/pigs-show
@@ -7,13 +7,13 @@ default_repo=".pig"
 
 if ! test -d "$default_repo"
 then
-    echo "$0: error: pigs repository directory $default_repo not found" >&2
+    echo "pigs-show: error: pigs repository directory $default_repo not found" >&2
     exit 1
 fi 
 
 if [ $# -ne 1 ] || ! echo "$@" | grep ':' > /dev/null
 then
-    echo "usage: $0 <commit>:<filename>">&2
+    echo "usage: pigs-show <commit>:<filename>">&2
     exit 1
 fi 
 
@@ -29,7 +29,7 @@ then
     index_file="$default_repo/index"
     if ! grep -E "^$file_name" "$index_file" > /dev/null
     then
-        echo "$0: error: '$file_name' not found in index" >&2
+        echo "pigs-show: error: '$file_name' not found in index" >&2
         exit 1 
     fi 
 
@@ -44,7 +44,7 @@ all_commits=$(cut -f1 -d' ' "$history_file")
 
 if ! echo "$all_commits" | grep -E "^$commit_num$" > /dev/null
 then
-    echo "$0: error: unknown commit '$commit_num'" >&2
+    echo "pigs-show: error: unknown commit '$commit_num'" >&2
     exit 1
 fi 
 
@@ -53,7 +53,7 @@ tree_referred="$default_repo/objects/$(sed -nE "s/^$commit_num (.*)$/\1/p" "$his
 all_files=$(cut -f1 -d' ' "$tree_referred")
 if ! echo "$all_files" | grep -E "^$file_name$" > /dev/null
 then
-    echo "$0: error: '$file_name' not found in commit $commit_num" >&2
+    echo "pigs-show: error: '$file_name' not found in commit $commit_num" >&2
     exit 1
 fi 
 
